### ISSUE TITLE
Procedure to submit new Alternative Payment in Shopify

### ISSUE THREAD

**Issue by jogam5** [Shopify/offsite_payments#131]
I wonder how I should proceed in order to propose a new Alternative Payment to Shopify (similar to Coinbase, GoCoin, etc.) I work at compropago.com: we make possible that online merchants receive cash payments in the biggest convenience store network across Mexico (~130,000 stores).
So far I think I should add compropago's integration to "offsite_payments" repo, then I can test how this (the integration) works via a simple rails app (or setting up a Spree store), is this right?
In case the answer is positive, what am I suppose to do next? What is the procedure you follow to review the new integrations, etc?
Thanks

**Comment by girasquid** [comment]
You'll be able to integrate faster if you take advantage of our universal offsite API - [this](https://github.com/Shopify/offsite-gateway-sim#getting-started) is a good guide to getting started with that.
