### ISSUE TITLE
MOLPay: Initial Commit

### ISSUE THREAD

**Issue by ntalbott** [Shopify/offsite_payments#32]
<a href="https://github.com/saifiikmal"><img src="https://avatars.githubusercontent.com/u/5268650?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [saifiikmal](https://github.com/saifiikmal)**
_Friday Apr 25, 2014 at 03:05 GMT_
_Originally opened as https://github.com/Shopify/active_merchant/pull/1143_

----

Please review as this is initial commit for MOLPay to Active Merchant. TQ

----

_**[saifiikmal](https://github.com/saifiikmal)** included the following code: https://github.com/Shopify/active_merchant/pull/1143/commits_

**Comment by girasquid** [comment]
MOLPay was merged; closing this.
